baseURL = "https://loganthorneloe.com"
title = "Logan Thorneloe"
theme = "hugo-theme-shell"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Logan Thorneloe's website"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
  scheme = "Molokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "logan"
  pcName = "dev"
  workDir = "src"
  profile = "readme.md"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 15 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  description = """

  Hi, I'm Logan Thorneloe!
  I'm a machine learning engineer,
  tech enthusiast, write, and 
  scientific researcher.
  
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "content"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Posts", "https://societysbackend.com/"],
    ["Projects", "/projects.md"],
    ["Work", "/work.md"],
  ]

  [Params.Tree2]
  use = true
  folderName = "connect"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [
    ["Substack", "https://substack.com/@loganthorneloe"],
    ["LinkedIn", "https://www.linkedin.com/in/loganthorneloe/"],
    ["Twitter/X", "https://twitter.com/@loganthorneloe"],
    ["GitHub", "https://github.com/lathorne"],
    ["YouTube", "https://www.youtube.com/channel/UC3H55I0SqNKQgJU77LsFiBw"],
    ["Reddit", "https://www.reddit.com/user/lathorne"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
