#!/usr/bin/env python3
"""Create a conservative public CV from the canonical private CV."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


PUBLIC_SECTIONS = (
    "Professional Summary",
    "Work Experience",
    "Publications",
    "Education",
    "Projects",
)

PRIVATE_FRAGMENTS = (
    "personal information",
    "star examples bank",
    "additional scholarships",
    "google lime scholar",
    "disability honor society",
    "disabilities",
    "need-based",
    "lime connect",
    "sensitive-data",
    "privacy constraints",
    "priority inversion",
    "antigravity",
    "proxy-task",
)

CURRENT_ROLE_PRIVATE_FRAGMENTS = (
    "agent-impact",
    "google deepmind",
    "infrastructure priorities",
    "large-scale ux",
    "leadership reporting",
    "platform datastore",
    "research trajectory",
    "technical leads",
    "user journey",
)

EMAIL_RE = re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.I)
PHONE_RE = re.compile(r"(?<!\d)(?:\+?1[-. (]*)?\d{3}[-. )]*\d{3}[-. ]*\d{4}(?!\d)")
SECRET_RE = re.compile(r"\b(?:github_pat_|gh[oprsu]_|sk-)[A-Za-z0-9_-]+\b")
LOCATION_RE = re.compile(
    r"^(?:Remote|[A-Z][A-Za-z .'-]+,\s*(?:[A-Z]{2}|[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?))\s*$"
)
NUMBER_RE = re.compile(r"\d")

HEADER = """# Logan Thorneloe

[GitHub](https://github.com/loganthorneloe) · [LinkedIn](https://linkedin.com/in/loganthorneloe) · [AI for Software Engineers](https://aiforswes.com)

<!-- Generated from the canonical resume repository. Do not edit this file directly. -->"""


def split_sections(source: str) -> dict[str, str]:
    matches = list(re.finditer(r"^## ([^\n]+)\s*$", source, re.MULTILINE))
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(source)
        sections[match.group(1).strip()] = source[start:end].strip()
    return sections


def contains_private_fragment(line: str) -> bool:
    lowered = line.lower()
    return any(fragment in lowered for fragment in PRIVATE_FRAGMENTS)


def is_location(line: str) -> bool:
    return bool(LOCATION_RE.fullmatch(line.strip()))


def normalize_blank_lines(lines: list[str]) -> str:
    normalized: list[str] = []
    previous_blank = True
    for raw_line in lines:
        line = raw_line.rstrip()
        is_blank = not line
        if is_blank and previous_blank:
            continue
        normalized.append(line)
        previous_blank = is_blank
    while normalized and not normalized[-1]:
        normalized.pop()
    return "\n".join(normalized)


def sanitize_common(content: str) -> str:
    lines = []
    for line in content.splitlines():
        if is_location(line) or contains_private_fragment(line):
            continue
        lines.append(line)
    return normalize_blank_lines(lines)


def sanitize_summary(content: str) -> str:
    paragraphs = re.split(r"\n\s*\n", content)
    safe_paragraphs = []
    for paragraph in paragraphs:
        if contains_private_fragment(paragraph):
            continue
        safe_paragraphs.append(sanitize_common(paragraph))
    return "\n\n".join(paragraph for paragraph in safe_paragraphs if paragraph)


def sanitize_work_experience(content: str) -> str:
    lines: list[str] = []
    current_role = ""

    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("### "):
            current_role = stripped[4:].lower()

        if is_location(line) or contains_private_fragment(line):
            continue

        if stripped.startswith("- ") and current_role.startswith("google ads"):
            lowered = stripped.lower()
            if NUMBER_RE.search(stripped):
                continue
            if any(fragment in lowered for fragment in CURRENT_ROLE_PRIVATE_FRAGMENTS):
                continue

        lines.append(line)

    return normalize_blank_lines(lines)


def sanitize_education(content: str) -> str:
    lines: list[str] = []
    skip_subsection = False

    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("#### "):
            skip_subsection = stripped == "#### Additional Scholarships"
            if skip_subsection:
                continue
        if skip_subsection or is_location(line) or contains_private_fragment(line):
            continue
        lines.append(line)

    return normalize_blank_lines(lines)


def assert_safe(public_cv: str) -> None:
    problems: list[str] = []
    if EMAIL_RE.search(public_cv):
        problems.append("email address")
    if PHONE_RE.search(public_cv):
        problems.append("phone number")
    if SECRET_RE.search(public_cv):
        problems.append("credential-like token")

    lowered = public_cv.lower()
    leaked_fragments = [fragment for fragment in PRIVATE_FRAGMENTS if fragment in lowered]
    problems.extend(f"private fragment: {fragment}" for fragment in leaked_fragments)

    leaked_locations = [line for line in public_cv.splitlines() if is_location(line)]
    problems.extend(f"location: {line}" for line in leaked_locations)

    if problems:
        raise ValueError("Refusing to publish CV containing " + ", ".join(problems))


def build_public_cv(source: str) -> str:
    sections = split_sections(source)
    missing = [name for name in PUBLIC_SECTIONS if name not in sections]
    if missing:
        raise ValueError("Missing required CV sections: " + ", ".join(missing))

    rendered = [HEADER]
    for name in PUBLIC_SECTIONS:
        content = sections[name]
        if name == "Professional Summary":
            content = sanitize_summary(content)
        elif name == "Work Experience":
            content = sanitize_work_experience(content)
        elif name == "Education":
            content = sanitize_education(content)
        else:
            content = sanitize_common(content)
        rendered.extend((f"## {name}", content))

    public_cv = "\n\n".join(rendered).strip() + "\n"
    assert_safe(public_cv)
    return public_cv


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Path to the canonical CV.md")
    parser.add_argument("output", type=Path, help="Path for the public CV.md")
    parser.add_argument("--check", action="store_true", help="Fail if output is not current")
    args = parser.parse_args()

    try:
        public_cv = build_public_cv(args.source.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        print(f"CV sync failed: {error}", file=sys.stderr)
        return 1

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != public_cv:
            print(f"{args.output} is out of date", file=sys.stderr)
            return 1
        return 0

    args.output.write_text(public_cv, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
